### ISSUE TITLE
Injected stylesheet messes up layout of some websites

### ISSUE THREAD

**Issue by Middlerun** [abhinavsharma/hypersearch#5]
**Describe the bug**
This extension injects this style into every website:

```css
html, body {
    width: 100% !important;
    max-width: 100% !important;
}
```

This messes up the layouts of some websites. A particularly bad example is https://xkcd.com/

**To Reproduce**
1. Have Hyperweb enabled
2. Go to https://xkcd.com/

**Expected behavior**
Layout is unaffected.

**Screenshots**

![xkcd](https://user-images.githubusercontent.com/568499/178137470-f288cfa2-3492-478c-a795-9094ed4325ce.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Firefox
 - Version: Chrome 103, Firefox 103

**Smartphone (please complete the following information):**
Untested
